### PR TITLE
fix non conventions based SentryLog engine

### LINKED ISSUE #57: Unable to use short name `CakeSentry.Sentry` for the `SentryLog` log engine
That's because the class in under the namespace `CakeSentry\Log\Engines` (plural "Engines") instead of `CakeSentry\Log\Engine` as per convention.

### PR DESCRIPTION
**Pull request by LordSimal**
Closes https://github.com/LordSimal/cakephp-sentry/issues/57

### CODE REVIEW

**Comment by LordSimal** [comment]
@ADmad looks good?

File: src/Log/Engine/SentryLog.php [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+            LogLevel::NOTICE, LogLevel::INFO => $sentryLogger->info($message, [], $context),
+            LogLevel::DEBUG => $sentryLogger->debug($message, [], $context),
+            default => $sentryLogger->trace($message, [], $context),
+        };
+
+        if (!$this->logsWillBeFlushed) {
+            $sentryLogger->flush();
+        }
+    }
+}
```
Comment (ADmad) [inline src/Log/Engine/SentryLog.php:60]: `class_alias()` call missing at the bottom of the file, similar to https://github.com/cakephp/cakephp/blob/5.next/src/Console/Helper/BannerHelper.php#L110

Comment (LordSimal) [reply src/Log/Engine/SentryLog.php:60]: done

File: src/Log/Engines/SentryLog.php [hunk 2]
```diff
@@ -3,58 +3,10 @@
...
-use Sentry\Logs\Logs;
-use Stringable;
+use CakeSentry\Log\Engine\SentryLog;
+use function Cake\Core\deprecationWarning;
 
-class SentryLog extends BaseLog
-{
-    public bool $logsWillBeFlushed = false;
+$msg = 'Use `CakeSentry\Log\Engine\SentryLog` instead of `CakeSentry\Log\Engines\SentryLog`.';
+deprecationWarning('3.5.3', $msg);
```
Comment (ADmad) [inline src/Log/Engines/SentryLog.php:10]: People usually don't like explicit deprecation warnings in a patch release.

Comment (LordSimal) [reply src/Log/Engines/SentryLog.php:10]: Then people can complain about that to me 😉
